### PR TITLE
vendor: Update vendoring for virtcontainers

### PR DESCRIPTION
**Pull request by amshinde**
Its been a while since we vendored virtcontainers.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/184/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent) [Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/184/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by sboeuf** [comment]
Side note: we might want to stick to specific versions for the vendoring. This should be done in a different PR, I am not expecting this for this PR.

**Comment by amshinde** [comment]
Yup that will be done in a separate PR. I want to update the other vendored packages as well, as we havent done that in a while. Will send out a separate PR for that.

**Comment by amshinde** [comment]
@sboeuf Can you merge?

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
