### PR TITLE
network: Don't try to replace initial existing routes

### LINKED ISSUE #86: Fix failing routes setup
The routes setup was failing after we have been replacing the initial route by the same one but without giving the source. Indeed, this initial route is setup when the interface is added, and it does not need to be replaced/overridden by the one provided through the `startpod` command. We skip this entry from the provided route list, allowing all the following routes to be properly added/replaced.

### PR DESCRIPTION
**Pull request by sboeuf**
Everytime an IP address is created for a specific interface, a route
is created accordingly. Because this route is a reference, we don't
want to modify it when applying the route list provided by the
startpod command. Instead, we ignore this specific entry from the
route list.

Fixes #86

### CODE REVIEW

**Comment by sboeuf** [comment]
Also fixes https://github.com/clearcontainers/runtime/issues/432

**Comment by sboeuf** [comment]
@amshinde please take a look.

**Review by egernst — COMMENTED** [review]
lgtm

Thanks sboeuf

**Review by amshinde — APPROVED** [review]
lgtm

**Comment by egernst** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/87/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Pull request merged**
