### PR TITLE
CI: Add additional project approvers

### LINKED ISSUE #44: Add additional project approvers
Add @dlespiau and @grahamwhaley as project approvers.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add @dlespiau and @grahamwhaley as additional project approvers.

Fixes #44.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by sboeuf** [comment]
I am okay with adding several approvers/reviewers but everybody needs to be careful about merging some patches on this repo because we don't have any CI right now and I don't want things to end up broken.
Other than that, you need to rebase your PR I think.
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent) [Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Review by sboeuf — APPROVED** [review]

**Comment by jcvenegas** [comment]
added #55 to add ci for testing.

**Comment by grahamwhaley** [comment]
Hah, looks like @jcvenegas beat me to opening the 'add CI' Issue :-)
@jodh-intel this looks like it needs a rebase (hmm, actually, isn't there a github setting that @dlespiau chanced on the clearcontainers/tests repo recently to only block merges if they are not merge-able, rather than if they are just 'out of date' (but potentially still merge-able)... /me goes to look at the settings...

**Pull request merged**
