### PR TITLE
.ci: Set CI env variable from run.sh

### LINKED ISSUE #152: ci: Set CI=true from run.sh
We need `CI=true` to be exported from `run.sh` so that we can have the CI running properly. Otherwise, we get a lot of warning from the Go metalinters.

### PR DESCRIPTION
**Pull request by sboeuf**
Force CI=true from run.sh since this script is only called in a CI
context.

Fixes #152

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/153/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by grahamwhaley** [comment]
@jodh-intel @sboeuf @chavafg - can I check if this is directly related to this recent PR from me where I unset `CI` in the Jenkins script - maybe it was needed and we missed it - maybe reverting that is the right thing...?

https://github.com/clearcontainers/tests/pull/668/commits/13828f06e7e3b9af626e601faa2123c377015faa
https://github.com/clearcontainers/tests/pull/668

**Comment by sboeuf** [comment]
@grahamwhaley yes it is directly related. And I realize now that we are not generating coverage if CI is not set for runtime for example. Please revert this part (I mean submitting a new patch for re-adding CI=true) and I'll drop this PR.

**Comment by sboeuf** [comment]
We can now close this PR as the fix has been merged through `tests` repo.

**Pull request closed without merging**
