### PR TITLE
agent-cli: Update documentation

### LINKED ISSUE #140: Update agent-cli documentation

### PR DESCRIPTION
**Pull request by sboeuf**
We have made few changes in our clear containers environment that
needs to be reflected here through our documentation.

Fixes #140

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm.

Aside: it might be worth moving that crazy-long `qemu` command to a script and having the doc reference it. That way:

- the doc is cleaner.
- you could require a rootfs arg for the script.
- the script could be tested.
- you could document all the qemu options for clarity.


[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/141/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by sboeuf** [comment]
@amshinde could you take a look ?

**Comment by sboeuf** [comment]
@iphutch could you take a look ?

**Review by iphutch — APPROVED** [review]
Changes look good.  What I would like to see is a change at line 19 from "your rootfs" to `<your_rootfs>`.

**Comment by sboeuf** [comment]
@iphutch Yes sure, I can include this change in this PR!

**Comment by sboeuf** [comment]
@iphutch I have made the change

**Comment by amshinde** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/141/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent) [Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/141/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Review by amshinde — APPROVED** [review]
lgtm

**Pull request merged**
