### PR TITLE
pullapprove: Add a new approver

### LINKED ISSUE #155: Add new pull request approver
I would like @jcvenegas to be added to the list of approvers on this repo.

### PR DESCRIPTION
**Pull request by sboeuf**
@jcvenegas has been contributing quite a lot to this repo and he
knows the code pretty well. That's why I would like him to be
an approver on this repo.

Fixes #155

### CODE REVIEW

**Comment by gorozco1** [comment]
👍

**Comment by jodh-intel** [comment]
Can you also add him to the `OWNERS` file?

**Comment by grahamwhaley** [comment]
agree, let's amend the OWNERS as well, then all good.

**Comment by sboeuf** [comment]
@grahamwhaley @jodh-intel yes I forgot that file... I have just updated the PR.

**Review by jodh-intel — APPROVED** [review]

**Review by grahamwhaley — APPROVED** [review]
lgtm

**Comment by grahamwhaley** [comment]
weird CI F26 timeout go error - I'll give it a rebuild kick to see if it was sporadic...
```
13:32:17 touch "/home/jenkins/jenkins_slave/workspace/clear-containers-agent-fedora-26-PR/go/.gopathok"
13:32:17 if [ ! -x "/home/jenkins/jenkins_slave/workspace/clear-containers-agent-fedora-26-PR/go/bin/git-validation" ]; then \
13:32:17 	go get -u github.com/vbatts/git-validation; \
13:32:17 fi
13:32:33 package golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp: lookup golang.org on 168.63.129.16:53: read udp 10.0.0.12:33267->168.63.129.16:53: i/o timeout)
13:32:34 make: *** [Makefile:203: .install.gitvalidation] Error 1
```

**Pull request merged**
