### PR TITLE
Use RouteAdd instead of RouteReplace while adding network routes

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent) [Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by mcastelino** [comment]
LGTM. I should have caught this earlier. Sorry

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent) [Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by jodh-intel** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/183/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by amshinde** [comment]
I am seeing the merge button disabled. Can someone merge this?

**Comment by mcastelino** [comment]
LGTM

**Review by mcastelino — APPROVED** [review]
LGTM

**Pull request merged**
