### PR TITLE
agent: Update libcontainer and remove the reaper fix

### LINKED ISSUE #88: Don't need to reap the zombie child anymore since libcontainer has been fixed
We had to reap the child zombie process because we were leaving some defunct child processes behind after we have started some processes. The reason was that libcontainer was not doing this for us.
It now has been fixed in libcontainer and we don't need our fix anymore.

### PR DESCRIPTION
**Pull request by sboeuf**
The latest version of libcontainer introduces a fix to reap the
defunct child process so that we don't have to do that from our
agent anymore.

This is pretty logical since the lib is starting the process on
our behalf, therefore they know they are leaving a zombie process
behind.

Fixes #88

### CODE REVIEW

**Comment by sboeuf** [comment]
@amshinde @jcvenegas please take a look.

**Comment by sboeuf** [comment]
https://github.com/opencontainers/runc/pull/1506 is the fix in libcontainer allowing this PR.

**Comment by jcvenegas** [comment]
@sboeuf  you hit travis `Invalid revision range` issue, could you update your PR?

**Comment by jcvenegas** [comment]
@GabyCT ping we will need to run your soak test.

**Comment by GabyCT** [comment]
@jcvenegas you can find the test at https://github.com/clearcontainers/tests/tree/master/integration/stability

**Review by amshinde — APPROVED** [review]
lgtm

**Comment by egernst** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/89/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Pull request merged**
