### PR TITLE
ci: teardown: put back most recent image

### PR DESCRIPTION
**Pull request by jcvenegas**
Add teardown script to put back the most recent image.

Fixes: #97

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/98/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent) [Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/98/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)

**Comment by jcvenegas** [comment]
@sboeuf @devimc @amshinde  semaphore failed in crio tests number 8
```
not ok 8 ctr list filtering
# (in test file crio.bats, line 373)
#   `[ "$status" -eq 0 ]' failed
```
Is there a documented  issue about it ?

**Comment by jcvenegas** [comment]
@sboeuf I also see jenkins failing in integration tests. I guess jeninks is still working progress.

**Comment by devimc** [comment]
@jcvenegas crio tests fail randomly in semaphore

**Comment by jcvenegas** [comment]
@devimc  do you know if is a documented random issue, or do you want me to create a issue about that ?

**Comment by devimc** [comment]
@jcvenegas  I don't know if there is a issue, feel free to file a new one

**Comment by jcvenegas** [comment]
@sboeuf could you merge this PR?

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
