### PR TITLE
Release: 0.1.1

### LINKED ISSUE #136: Agent 0.1.1
Create a new release for agent is need for last important fixes.

### PR DESCRIPTION
**Pull request by jcvenegas**
- ci: Standardize agent timeouts to 15 seconds
- exit: Ignore ExitError error type
- exit: Check if process was signaled
- agent: Discard signals if cannot find sequence ID
- agent-cli: Update documentation
- agent: re-scan pci bus to discover hidden devices
- devices: Add extra field in fsmap to directly mount devices.
- logging: Simplify error logging
- target: Add clr-power-tweaks add target depedency.
- logging: Add name and PID fields
- kill: fix sporadic deadlock related to freezer cgroup issue
- readme: Update build badges
- logging: use structured logging
- .ci: Allow fedora support in setup.sh script
- ci: teardown: put back most recent image
- readme: Replace Travis build badges with Jenkins ones

cd3bf64 ci: Standardize agent timeouts to 15 seconds
47d1851 exit: Ignore ExitError error type
6fe454f exit: Check if process was signaled
fd4925e agent: Discard signals if cannot find sequence ID
e43e8b2 agent-cli: Update documentation
047864c agent: re-scan pci bus to discover hidden devices
a01050d devices: Add extra field in fsmap to directly mount devices.
a4e5c71 logging: Simplify error logging
1cd5c1d target: Add clr-power-tweaks add target depedency.
c2c50e9 logging: Add name and PID fields
b8fb00e kill: Prevent deadlock while waiting for kill command
742cbc8 vendor: Update runc vendoring
ab20289 readme: Update build badges
59a4018 logging: use structured logging
2e9424a .ci: Allow fedora support in setup.sh script
b30976e ci: teardown: put back most recent image
8a627b6 readme: Replace Travis build badges with Jenkins ones

Fixes: #136

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Review by gorozco1 — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
Shouldn't we consider aligning this version number with that of the other components?

/cc @sboeuf, @grahamwhaley, @sameo

**Comment by grahamwhaley** [comment]
my gut feeling is, yes. If we have taken the decision to align all the other components, even bumping an individual components number when there have been no changes in it, then it makes sense to me to keep all components, including the agent, in line with that.

**Comment by jcvenegas** [comment]
@jodh-intel  @grahamwhaley  I like the idea.  @sboeuf  do you have any comment related about that?.

**Review by sboeuf — APPROVED** [review]

**Pull request merged**
